// Generated by Convex - Placeholder for build
// Run `npx convex dev --once --configure=new` to generate real types

export const api = {} as any;
export const internal = {} as any;

export type Id<TableName extends string = string> = string & { __tableName: TableName };